apiVersion: v1
kind: ConfigMap
metadata:
  namespace: healthcare-hlf
  name: ca-client-config-payer
data:
  config.json: |-
      {
      "request-timeout" : 30000,
      "tcert-batch-size" : 10,
      "crypto-hash-algo": "SHA2",
      "crypto-keysize": 256,
      "crypto-hsm": false,
      "connection-timeout": 30000
      }